CREATE TABLE IF NOT EXISTS "Eod"(
    "basisofrecord" TEXT,
    "institutioncode" TEXT,
    "collectioncode" TEXT,
    "catalognumber" TEXT,
    "occurrenceid" TEXT,
    "recordedby" TEXT,
    "year" TEXT,
    "month" TEXT,
    "day" TEXT,
    "publishingcountry" TEXT,
    "country" TEXT,
    "stateprovince" TEXT,
    "county" TEXT,
    "decimallatitude" TEXT,
    "decimallongitude" TEXT,
    "locality" TEXT,
    "kingdom" TEXT,
    "phylum" TEXT,
    "class" TEXT,
    "order" TEXT,
    "family" TEXT,
    "genus" TEXT,
    "specificepithet" TEXT,
    "scientificname" TEXT,
    "vernacularname" TEXT,
    "taxonremarks" TEXT,
    "taxonconceptid" TEXT,
    "individualcount" TEXT
);
CREATE TABLE IF NOT EXISTS "Birdfeeder"(
    "LOC_ID" TEXT,
    "LATITUDE" TEXT,
    "LONGITUDE" TEXT,
    "SUBNATIONAL1_CODE" TEXT,
    "ENTRY_TECHNIQUE" TEXT,
    "SUB_ID" TEXT,
    "OBS_ID" TEXT,
    "Month" TEXT,
    "Day" TEXT,
    "Year" TEXT,
    "PROJ_PERIOD_ID" TEXT,
    "SPECIES_CODE" TEXT,
    "alt_full_spp_code" TEXT,
    "HOW_MANY" TEXT,
    "PLUS_CODE" TEXT,
    "VALID" TEXT,
    "REVIEWED" TEXT,
    "DAY1_AM" TEXT,
    "DAY1_PM" TEXT,
    "DAY2_AM" TEXT,
    "DAY2_PM" TEXT,
    "EFFORT_HRS_ATLEAST" TEXT,
    "SNOW_DEP_ATLEAST" TEXT,
    "Data_Entry_Method" TEXT
);
CREATE TABLE IF NOT EXISTS "Taxonomy"(
    "TAXON_ORDER" TEXT,
    "CATEGORY" TEXT,
    "SPECIES_CODE" TEXT,
    "TAXON_CONCEPT_ID" TEXT,
    "PRIMARY_COM_NAME" TEXT,
    "SCI_NAME" TEXT,
    "ORDER" TEXT,
    "FAMILY" TEXT,
    "SPECIES_GROUP" TEXT,
    "REPORT_AS" TEXT
);